OPENAI_API_KEY = "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"
KAKAO_REST_API_KEY = "1190938b09ae456e15b6c57604e5dacd"